### PR TITLE
#50 db access class

### LINKED ISSUE #50: DB-Access class
Implementing a class that handles all database connections.

### PR DESCRIPTION
**Pull request by TobiasLang97**
Created a database class which creates the database connection in the constructor and execute queries using the executeQuery(String, $query, Array $params) method.

### CODE REVIEW

**Comment by ghost** [comment]
Please provide at least a *basic* description of the implementation here.

**Review by MarcelMoeller — CHANGES_REQUESTED** [review]
**EDIT: Comment is obsolete. Changes where already made.**

The current implementation does not work because the variables in line 24 are not existing at the moment. Instead of using **$host**, **$this->host** should be used. This way the properties of the class are used instead of local variables.

**Review by MarcelMoeller — CHANGES_REQUESTED** [review]
The method strpos in line 50 expects two parameters. So instead of **strpos($key == ':')**, **strpos($key, ':')** should be used.

**Comment by ghost** [comment]
Good work guys, merging this and closing the issue.

**Pull request merged**
