### PR TITLE
Refactoring autoloader

### PR DESCRIPTION
**Pull request by daniel100097**

### CODE REVIEW

**Comment by daniel100097** [comment]
Autoloader from PSR4
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md

Classes are now loaded from src automaticly

**Comment by ghost** [comment]
This Autoloader implementation would completly replace the one by @MarcelMoeller.
Review has been requested, please decide the way you want to use going forward.

**Comment by ghost** [comment]
Reopened https://github.com/Eckener-Schule/it-ausleihe/issues/55 for now.

**Comment by daniel100097** [comment]
Autoloader are merged, after discussion with @MarcelMoeller.

Both autoloaders are used for this project. Old legacy classes are loaded from classes, and PSR-4 code is loaded from src

**Comment by ghost** [comment]
Using multiple different autoloaders for a project of this size is a bit bloated in my view, but a decision that has to be made by the development team.
Awaiting the response by @MarcelMoeller before I merge this.

**Review by MarcelMoeller — CHANGES_REQUESTED** [review]
This change should work for the beginning. As soon as the basic structur of the project is implemented it should be decided as soon as possible if the project will use psr-4 namespaces so we can remove one of the autoloaders.

Also it might make sense to change the hardcoded directory separators to the magic constant **DIRECTORY_SEPARATOR** in line 30 of the autoloader file to prevent something like **\it-ausleihe/src/Cart.php** on different operating systems.

To prevent unnecessary code it would also make sense to link an example inside the readme instead of implementing an empty class without any usage.

**Comment by daniel100097** [comment]
Windows's can understand the unix directory separator, so it's unnecessary to use the os specific seperator.

https://alanhogan.com/tips/php/directory-separator-not-necessary

**Comment by daniel100097** [comment]
It makes sense to use only one autoloader, the team has to decide if they want to follow PSR-4.

The change to PSR-4 would result in a change of all existing classes.

**Comment by daniel100097** [comment]
The team has voted against the PSR-4 autoloader.

**Comment by ghost** [comment]
I take it the issue has been resolved, merge approved and issue #55 will be closed.

**Pull request merged**
